<a href="https://colab.research.google.com/github/sabhinav3/Intro_to_ML/blob/main/assignment_5_3_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load your data
data = pd.read_csv("/content/Housing.csv")

In [2]:
data = pd.get_dummies(data)
data

,price,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,0,1,1,0,...,0,1,0,0,1,0,1,1,0,0
1,12250000,8960,4,4,4,3,0,1,1,0,...,0,1,0,0,1,1,0,1,0,0
2,12250000,9960,3,2,2,2,0,1,1,0,...,1,1,0,1,0,0,1,0,1,0
3,12215000,7500,4,2,2,3,0,1,1,0,...,1,1,0,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,0,1,0,1,...,1,1,0,0,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,0,1,1,0,...,1,1,0,1,0,1,0,0,0,1
541,1767150,2400,3,1,1,0,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
542,1750000,3620,2,1,1,0,0,1,1,0,...,0,1,0,1,0,1,0,0,0,1
543,1750000,2910,3,1,1,0,1,0,1,0,...,0,1,0,1,0,1,0,1,0,0
544,1750000,3850,3,1,2,0,0,1,1,0,...,0,1,0,1,0,1,0,0,0,1

In [3]:

# Splitting the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(data.drop("price",axis=1), data["price"], test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

In [4]:
# Initialize variables to store the best model and its performance
best_model = None
best_val_loss = float('inf')  # Initialize with a large value

# Loop through different learning rates
learning_rates = [0.1, 0.01, 0.001,0.0001]
for learning_rate in learning_rates:
    # Create and train the model
    model = LinearRegression()
      # Update the model using the entire dataset
    model.fit(X_train_scaled, y_train)
    # Training loop
    for epoch in range(5001):
        # Predict and evaluate the model
        y_train_pred = model.predict(X_train_scaled)
        y_val_pred = model.predict(X_val_scaled)

        # Calculate performance metrics every 500 epochs
        if epoch % 500 == 0:
            train_mse = mean_squared_error(y_train, y_train_pred)
            val_mse = mean_squared_error(y_val, y_val_pred)
            train_r2 = r2_score(y_train, y_train_pred)
            val_r2 = r2_score(y_val, y_val_pred)

            print(f"\nLearning Rate: {learning_rate}, Epoch: {epoch}")
            print(f"Training MSE: {train_mse:.2f}, Training R²: {train_r2:.4f}")
            print(f"Validation MSE: {val_mse:.2f}, Validation R²: {val_r2:.4f}")

            # Check if the current model has lower validation loss
            if val_mse < best_val_loss:
                best_val_loss = val_mse
                best_model = model

Learning Rate: 0.1, Epoch: 0
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 1000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 1500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 2000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 2500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 3000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 3500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 4000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 4500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.1, Epoch: 5000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 0
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 1000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 1500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 2000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 2500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 3000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 3500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 4000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 4500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.01, Epoch: 5000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 0
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 1000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 1500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 2000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 2500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 3000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 3500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 4000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 4500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.001, Epoch: 5000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 0
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 1000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 1500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 2000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 2500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 3000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 3500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 4000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 4500
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

Learning Rate: 0.0001, Epoch: 5000
Training MSE: 968358188440.72, Training R²: 0.6859
Validation MSE: 1754318687330.67, Validation R²: 0.6529

In [5]:
# Printing information about the best model
if best_model:
    print("\nBest model setup:")
    print(f"Best Validation Loss: {best_val_loss:.4f}")
    print(f"Training Loss: {train_mse:.4f}")
    print(f"R² (R-squared) Validation: {val_r2:.4f} (higher is better)")
    # You can also print other information about the best model, e.g., learning rate, epoch, etc.
else:
    print("No results to report.")

Best model setup:
Best Validation Loss: 1754318687330.6689
Training Loss: 968358188440.7242
R² (R-squared) Validation: 0.6529 (higher is better)